#!/bin/bash
#SBATCH -J ssort_wc906     # job name
#SBATCH -o ssort_wc906.o%j # output and error file name (%j expands to jobID)
#SBATCH -n 64              # total number of mpi tasks requested
#SBATCH -p development     # queue (partition) -- normal, development, etc.
#SBATCH -t 00:30:00        # run time (hh:mm:ss) - 1.5 hours
#SBATCH --mail-user=cwk689@gmail.com
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes
#SBATCH -A TG-ASC150003    # account number
ibrun ./ssort              # run the MPI executable named a.out